### ISSUE TITLE
advice on error handling

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#31]
Hi, Paul

A quick consultation: I'm starting to test text.py against a larger range of texts, using the previous submissions to the IJAL texts online and TILA series. How do you think it is best to handle user errors like the one below? In a nutshell, what is happening is that the grammaticalTerms file provided by the user contains a tab (this will not be uncommon because many people will be creating these file from tables and tabbed lists). The tab breaks yaml.load(). It seems like the options are

1) Just check the file for tabs before feeding it to yaml and either 
     a) remove the tabs, 
     b) abort and warn the user,
     c) remove the tabs and warn the user that this is being done
2) trap the error, abort, and warn the user 

My inclination is towards 1a, but how would a real programmer do it? Given that I expect a lot of these kinds of small idiosyncratic things to start cropping up I should probably have a consistent and principled approach to them.

Cheers,

David

ERROR on upload grammatical terms

=== on_grammaticalTermsUpload
[2019-05-11 08:12:12,948] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 1151, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 1037, in add_context
    output_value = func(*args, **kwargs)
  File "webapp.py", line 638, in on_grammaticalTermsUpload
    yaml_list = yaml.load(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 11, column 5:
    APPL	
        ^

**Comment by paul-shannon** [comment]
I like option 1a as well.   I bet you have (or could easily) figure this out on your own, but just in case:

webapp.py gets the yaml string like this:

    encodedString = contents.encode("utf8").split(b";base64,")[1]
    decodedString = base64.b64decode(encodedString)
    s = decodedString.decode('utf-8')
    yaml_list = yaml.load(s)

add this:

    sNoTabs = s.replace(“\t”, “ “)
    yaml_list = yaml.load(sNoTabs)

You probably want to expand the unit test, to include this problem.  The string “s” - possibly with tabs - can be read like this:

    s = open("tierGuide-with-tabs.yaml").read()
    sNoTabs = s.replace(“\t”, “ “)
    yaml_list = yaml.load(sNoTabs)

It looks like yaml.load(x) works equally well for x as a file, and x as a string.  The tab protection form of the code, in test_IjalLine.py, needs only to shift to “x as a string”, where the string comes in through open(f).read(), then gets the remove-tabs treatment.

**Comment by davidjamesbeck** [comment]
Perfect, thanks. I see you suggest applying the string.replace() method all the time instead of making it conditional. I guess the test is just a waste of resources?

David

**Comment by paul-shannon** [comment]
Maybe not so much a waste of resources as it is extra coding complexity.  And since the yaml text is so small, we can do the replace operation, even when not needed, at no noticeable cost.
