### ISSUE TITLE
returning errors from "deep" methods

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#32]
Hi, Paul

So, I have found an .eaf file with an error in it, a mismatch between the number of tabbed words in the morpheme line and the number in the morphemeGlosses line. It would be nice to be able to tell the author exactly where and what the error is—is there some way to percolate that information up from IjalLine to the webapp so I can show it on the page?

David

eafFileName: PROJECTS/Inferno/JIT0006_ori.eaf
projectDirectory: PROJECTS/Inferno
audioDirectoryRelativePath: audio
grammaticalTermsFile: None
tierGuideFile: PROJECTS/Inferno/tierGuide.yaml
ijal.css
[2019-05-12 09:42:13,309] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/David/OpenSource/github/slexil/ijalLine.py", line 201, in calculateMorphemeSpacing
    assert(len(morphemes) == len(glosses))
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 1151, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 1037, in add_context
    output_value = func(*args, **kwargs)
  File "webapp.py", line 762, in createWebPageCallback
    os.path.join(projectDirectory, "tierGuide.yaml"))
  File "webapp.py", line 1031, in createWebPage
    return(text.toHTML())
  File "/Users/David/OpenSource/github/slexil/text.py", line 143, in toHTML
    line.parse()
  File "/Users/David/OpenSource/github/slexil/ijalLine.py", line 61, in parse
    self.calculateMorphemeSpacing()
  File "/Users/David/OpenSource/github/slexil/ijalLine.py", line 203, in calculateMorphemeSpacing
    raise Exception((morphemes,glosses)) from e
Exception: (['que', '∅–ʔa¢i=pɨʔ=ʔiṣ̌=tam=koʔ', 'que', 'heʔ', 'pɨn', 'y–¢am–hay–¢o¢–wɨ', 'y–yomo', 'que', 'ʔuy¢i', 'ʔak–toko–¢ɨk–i', 'mok', 'porque'], ['SUBORD', '3S–uncle=REL=ERG=PL=then', 'SUBORD', 'DEF', 'hombre', '3A–tell–APPL–begin–CMP', '3PSR–woman', 'SUBORD', 'NEG.IMP', '', 'CAUS–go.bad–do–DEP1', 'corn', 'because'])

**Comment by paul-shannon** [comment]
This is where exceptions are very useful.  They get thrown down deep, and when using a custom exception, you are free to add all the detail you know to that custom exception.  Then you catch the bouquet exception up high, in the ui, displaying all of that detal for the user's edification.

google "python custom exception" should give you a good start.

 - Paul

**Comment by davidjamesbeck** [comment]
Okay, I do know how to use exceptions, but I was under the impression that they were more local than that. If they don’t have to go back up the chain of methods via some kind of return function, then this should be easy to take care of. (Famous last words.)

Good thing, too, I’ve found this kind of mismatch error in 2/4 files I’ve tested so far.

Thanks!

David
